---

name: getting-help-build-deploy

on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: uplime/discord-webhook@v1.1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: notice
          message: Beginning the build process for the documents.
          format: true

      - name: Install dependencies required for building.
        id: install-build-dependencies
        run: |
          sudo apt install -y texlive-latex-base texlive-latex-extra
          sudo -E bin/tools/install-pandoc

      - name: Build document artifacts for deployment.
        id: build-artifacts
        run: |
          sudo -E make build

      - name: Store the build artifacts in a cache.
        id: store-artifact-cache
        uses: actions/upload-artifact@v3
        with:
          name: store-artifact-cache
          path: build

      - uses: uplime/discord-webhook@v1.1
        if: failure()
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: error
          message: There was a problem building the documents.
          format: true

      - uses: uplime/discord-webhook@v1.1
        if: success()
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: notice
          message: The documents were built successfully.
          format: true

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: uplime/discord-webhook@v1.1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: notice
          message: Deploying the built documents.
          format: true

      - name: Install dependencies required for building.
        id: install-build-dependencies
        run: |
          sudo apt install -y curl gpg librsvg2-bin

      - name: Configure AWS credentials for the Storage account.
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: us-west-2

      - name: Use the built cache.
        id: store-artifact-cache
        uses: actions/download-artifact@v3
        with:
          name: store-artifact-cache
          path: build

      - name: Deploy build artifacts.
        id: deploy-artifacts
        run: |
          sudo -E make deploy

      - uses: uplime/discord-webhook@v1.1
        if: failure()
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: error
          message: There was a problem deploying the documents.
          format: true

      - uses: uplime/discord-webhook@v1.1
        if: success()
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: notice
          message: The documents were deployed successfully.
          format: true
