---

name: getting-help-deploy

on:
  push:
    branches:
      - stable

env:
  IS_CI: yes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build artifacts from markdown file.
        id: build-artifacts
        run: |
          sudo -E make build

      - name: Setup the build cache.
        id: set-cache-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cache-artifacts
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials for the Storage account.
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: us-west-2

      - name: Retrieve the build cache.
        id: ret-cache-artifacts
        uses: actions/download-artifact@v3
        with:
          name: cache-artifacts

      - name: Deploy build artifacts.
        id: deploy-artifacts
        run: |
          sudo -E make deploy
