---

name: getting-help

on:
  pull_request:
    branches:
      - stable

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate and lint repository files.
        id: validate-files
        run: |
          make test

  build:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build artifacts from markdown file.
        id: build-artifacts
        run: |
          make build

#  deploy:
#    needs: build
#    runs-on: ubuntu
#
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Configure AWS credentials for the Storage account.
#        id: configure-aws
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: ${{ secrets.BKT_UPLOAD_ROLE }}
#          aws-region: ${{ secrets.BKT_REGION }}
#
#      - name: Put the build artifacts in their bucket.
#        run: |
#          make deploy
