---

name: getting-help-test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install repository dependencies.
        id: install-test-dependencies
        run: |
          sudo apt install -y shellcheck yamllint
          sudo -E bin/tools/install-typos-cli

      - name: Test and lint repository files.
        id: test-lint-check
        run: |
          sudo -E make test

      - uses: uplime/discord-webhook@v1.1
        if: failure()
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: error
          message: The submitted PR did not pass required tests.
          format: true

      - uses: uplime/discord-webhook@v1.1
        if: success()
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          name: Cloud Droid
          level: notice
          message: The submitted PR successfully passed all required tests.
          format: true
